apiVersion: v1
kind: ReplicationController
metadata:
  name: rng-rc
spec:
  replicas: 2
  selector:
    rng-key: rng-value
  template:
    metadata:
      labels:
        rng-key: rng-value
    spec:
      containers:
        -
          args:
            - rng.py
          command:
            - /usr/local/bin/python
          env:
            - 
              name: HELLO
              value: world
            - 
              name: AUTHOR
              value: Sebastian
          image: academiaonline/simplilearn-dockercoins:rng-test
          name: rng-container
          ports:
            - 
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 100M
            requests:
              cpu: 10m
              memory: 20M
          securityContext:
            runAsGroup: 1000620000
            runAsUser: 1000620000
          volumeMounts:
            -
              mountPath: /app/rng.py
              name: rng-volume
              readOnly: true
              subPath: rng.py
          workingDir: /app/
      volumes:
        -
          name: rng-volume
          secret:
            secretName: rng-secret
