################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
name: ci

on:
  push:
    branches:
      - docker
      
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
        
          set -x
          
          for app in hasher rng webui worker
            do
              docker build --tag academiaonline/simplilearn-dockercoins:latest-${app}-testing ${app}
            done

          for app in hasher redis rng
            do
              docker network create ${app}
            done
          
          app=redis
          docker run --detach --name ${app} --network ${app} --volume ${app}:/data ${app}
          
          for app in hasher rng
            do
              docker run --detach --name ${app} --network ${app} academiaonline/simplilearn-dockercoins:latest-${app}-testing
            done
            
          app=worker
          network=redis
          docker run --detach --name ${app} --network ${network} academiaonline/simplilearn-dockercoins:latest-${app}-testing
          for app in hasher rng
            do
              docker network connect ${app} worker
            done
          
          app=webui
          network=redis
          docker run --detach --name ${app} --network ${network} academiaonline/simplilearn-dockercoins:latest-${app}-testing

          app=worker
          pattern="Coin found"
          while true
            do
              sleep 10
              docker logs ${app} 2>& 1 | grep "${pattern}" && break
            done
